+++
title= "AI's feudal war for your soul and how to win it"
weight = 20
+++

Over the past five years the tech billionaires of Silicon Valley have been pushing for the mass adoption of AI, cryptocurrency, and the everyday use of virtual reality as a replacement for in-person human interaction. From Google and Apple to Nvidia and OpenAI, across the industry the push for AI has been omnipresent. Every social media platform, image editing software, and search engine seems to be teeming nowadays with AI summaries and creations. No matter where you look it seems in the span of only a couple years AI has wriggled its way into our lives. People may be confused as to why this has become the case. Many of those critical of AI chalk it up simply to the greed of billionaires and the corporations that run these AI services. Many people, however, simply accept the use of these technologies as a new fact of life. AI is simply another more convenient writing tool and search engine optimizer. Cryptocurrency is simply another investment that has bubbled up in the tech sphere. However the intentions of these billionaires and newly crowned oligarchs are much deeper than most think. 

## Kings are in America again…

The author of this new ideology which has won the hearts and minds of billionaires and halfwit freaks alike, Kurtis Yarvin, who also goes by his pen name, “Mencius Moldbug” (which is quite descriptive of him both in looks and in quality) has become a shadowy yet hugely influential voice among billionaire circles. On his blog he wrote “A century and a half of democracy has wreaked unbelievable devastation on a place and people once considered by far the most promising on earth” In 2017 he published his most popular work Patchwork: A Political System for the 21st Century wherein he describes his ideal neo-feudal system of governance which would replace our current worldwide democracies with feudal “sovereigns” ruled by corporate bosses like kings and use crypto as an official currency. In his book he even argued that “Since [people who are not capable of earning a living] are liabilities, there is no business case for retaining them in their present, ambulatory form. Therefore, the most profitable disposition for this dubious form of capital is to convert them into biodiesel, which can help power the Muni buses.” He afterwards called it a joke and decided that “The best humane alternative to genocide I can think of is not to liquidate the wards (unproductive adults)—either metaphorically or literally—but to virtualize them” and argues that unproductive adults should be improsined in virtual spaces indefinitely. 
Suffice it to say he’s a crank and did not get much public attention in 2017 for this work. However over the next 8 years, expedited immensely by Covid-19, tech companies ramped up the “war on our souls”. In 2021 the recently renamed Meta company launched their metaverse project which advocated the transition of human society into virtual worlds, the exact technology Moldbug proposed to use as psychological prisons of our own minds. In that same year El Salvador became the first country to accept bitcoin as legal tender. From 2022 onward AI image and text generation received massive investments, even in this very month when Trump stated that he would promise to invest $500 billion taxpayer dollars into corporations that produce AI products. Now the popularization of bitcoin and AI has reached every eye and ear in this country and Mr. Moldbug has been receiving much more attention as of late. Moldbug has caught the attention from the likes of Peter Thiel, prominent republican strategist, Steve Bannon, and our current Vice President JD Vance.
Now that Trump has taken office and Elon Musk with his billionaire cronies have taken root in the government, Moldbug has direct connections to the most powerful positions on the planet and has the ears of the tech billionaires and tech giants of silicon valley. With this unprecedented coup from the upper class, the power of the wealthiest corporations, and the most powerful country on the planet influenced by the moldy bugman monarchist there seems to be no stopping this steep decline in civilization. 
	The billionaires are now gearing up and building their power to form not only an oligarchical America but to revive from death a monarchical America. Even before Moldbug’s manifesto on techno-feudalism our connections with our fellow human beings have withered away with the mass adoption and now addiction of social media. Furthering this, the tech industry took every opportunity to break us apart. They separated us from our stores with Amazon and doordash, they separated us from our own communities with social media, and now they want to cut us off from the act of creating art itself. We no longer own the means of communicating with each other, or the movies we watch, or the art we see. They aim to break our creativity and drive for art, they want to wipe out our human desire to be heard, to be known, to participate in our own communities. They want to destroy all that is known to be human; our art, our writing, our intellect, our basic interactions with fellow humans must now be filtered through AI or technology that is owned by the most dangerous entities humanity has had the misfortune of breeding. They are waging a war for your soul. 

## How to win it

	
There is no death to change like apathy. We no longer have time to step back and reflect on our world. We, the American people, understand the world and we understand that it is broken. We understand then that there must be change, a movement to counteract this techno-feudalist takeover. So, where can we begin?
We must first take back the damage they have done in our own lives. Break from the psychological prisons they have put our minds in. Do not be docile, do not obey, engage with your neighbors and your own communities in real life. Buy from your local stores, make your own art, ask real people for advice not the robots made of an anti-human design. Do not listen to their machines of despair. Do not give in to their campaign of fear. A better future can only begin with the faith in that reality.
We must then organize each other. Pressure your local representatives for change, help your local community when they need help, advocate for our streets to care about the citizens living in them not the metal boxes that move through them, ban the use of AI in your school or workplace. We must build the strength of cooperation once again to begin to strive for our democratic future. Cooperation is the fundamental principle that has made us the most powerful species on Earth and only with that power can we turn the world towards us.
We must declare war on the monarchists and the billionaires. We must not bend to their will. Not only will we have to take back the democracy they have stolen from us, we must fight to expand democracy. We must fight for democracy in our schools, in our neighborhoods, in our workplaces, in all aspects of our lives. We will only ever win when the democracy of the government is matched and exceeded by the democracy of our economy. When the flow of information and commerce is democratically controlled by every worker in every country. When we all have equal say in all of our respective workplaces and when the bosses no longer exist. This is the fight the IWW wages. We hold democracy on its rightful pedestal, our shining beacon on the hill. We are the true bearers of the torch of liberty and we have been for the past 120 years. We will not let this light extinguish and we will continue to wage the war for humanity. We are here and we are ready. 
