# Build site using Zola and deploy to S3 bucket with website hosting configured
# Configure the listed secret values to deploy.
# The IAM user associated with the access key should ONLY have the following permissions,
# scoped to the bucket and its objects:
# * s3:DeleteObject
# * s3:GetObject
# * s3:ListBucket
# * s3:PutObject

name: Deploy

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Run Zola
        run: |
          sudo snap install --edge zola
          zola build
      - name: deploy to pages
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Deploy to hosting S3 bucket
        uses: reggionick/s3-deploy@v3
        with:
          folder: public
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: us-east-2
          # dist-id: ${{ secrets.CLOUDFRONT_CDN_ID }}
          # invalidation: '/*'
          # delete-removed: true
